// <auto-generated />
using System;
using InsuranceApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsuranceApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260923125210_AddBrokers")]
    partial class AddBrokers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.BrokerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .UseCollation("C");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_brokers_code");

                    b.HasIndex("Name", "Id");

                    b.ToTable("brokers", null, t =>
                        {
                            t.HasCheckConstraint("ck_brokers_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.BuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("integer")
                        .HasColumnName("construction_year");

                    b.Property<decimal>("InsuredValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("insured_value");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_floors");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<decimal>("SurfaceArea")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("surface_area");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClientId", "Id");

                    b.ToTable("buildings", null, t =>
                        {
                            t.HasCheckConstraint("ck_buildings_construction_year", "construction_year BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("ck_buildings_insured_value", "insured_value > 0");

                            t.HasCheckConstraint("ck_buildings_number_of_floors", "number_of_floors >= 1");

                            t.HasCheckConstraint("ck_buildings_surface_area", "surface_area > 0");

                            t.HasCheckConstraint("ck_buildings_type", "type IN ('Residential', 'Office', 'Industrial')");
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid")
                        .HasColumnName("county_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountyId", "Name")
                        .IsUnique();

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333333"),
                            CountyId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Name = "Cluj-Napoca"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333334"),
                            CountyId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Name = "Turda"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333335"),
                            CountyId = new Guid("22222222-2222-4222-8222-222222222223"),
                            Name = "Debrecen"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333336"),
                            CountyId = new Guid("22222222-2222-4222-8222-222222222223"),
                            Name = "Hajdúszoboszló"
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identification_number")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("primary_address");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_clients_identification_number");

                    b.HasIndex("Name", "Id");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_clients_type", "type IN ('Individual', 'Company')");
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111112"),
                            Name = "Hungary"
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.CountyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("counties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            CountryId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Name = "Cluj"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222223"),
                            CountryId = new Guid("11111111-1111-4111-8111-111111111112"),
                            Name = "Hajdú-Bihar"
                        });
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.BuildingEntity", b =>
                {
                    b.HasOne("InsuranceApp.Infrastructure.Persistence.Entities.CityEntity", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_cities_city_id");

                    b.HasOne("InsuranceApp.Infrastructure.Persistence.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buildings_clients_client_id");
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.CityEntity", b =>
                {
                    b.HasOne("InsuranceApp.Infrastructure.Persistence.Entities.CountyEntity", null)
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceApp.Infrastructure.Persistence.Entities.CountyEntity", b =>
                {
                    b.HasOne("InsuranceApp.Infrastructure.Persistence.Entities.CountryEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
